[package]
name = "swc-reanimated-worklets-visitor"
version = "0.0.1"
edition = "2021"
authors = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = ""
license = "MIT"
repository = "https://github.com/kwonoj/swc-plugin-react-native-reanimated"

[dependencies]
swc_common = "0.18.7"
swc_ecma_transforms_compat = "0.101.1"
swc_ecmascript = { version = "0.159.0", features = ["utils", "visit"] }
swc_visit = "0.3.0"
