[package]
name = "swc-reanimated-worklets-visitor"
version = "0.0.1"
edition = "2021"
authors = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = ""
license = "MIT"
repository = "https://github.com/kwonoj/swc-plugin-react-native-reanimated"

[dependencies]
swc_ecmascript = "0.159.0"
